version: '3.9'

services:
  authenticator:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8006:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
    networks:
      - stackoverflow
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 6543:5432
    networks:
      - stackoverflow
volumes:
  postgres_data:


networks:
  stackoverflow:
    driver: bridge
