# Generated by Django 4.1.3 on 2023-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permission_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
