# Generated by Django 4.1.3 on 2023-06-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_permission_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
