# Generated by Django 4.1.3 on 2023-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(default='https://i.pravatar.cc/200', max_length=100),
        ),
    ]
