# Generated by Django 4.1.3 on 2023-08-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_account_status_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidationstatus',
            name='validation_status',
            field=models.BooleanField(default=False),
        ),
    ]
